### PR TITLE
PHP versioning, little cleanup

### PR DESCRIPTION
**Pull request by willmorgan**
* Markdown has been changed slightly so there's no horizontal scrollbar in the README viewer.
* The "Purpose" column on the README was a bit much and didn't have much use, so it's been removed
* The default version of PHP has been shifted to PHP 5.6, with 5.5 and 5.3 scripts provided. All `php-x.sh` scripts have been suffixed with their versions.
* Mcrypt is now installed by default for 5.5 >=

### CODE REVIEW

**Comment by willmorgan** [comment]
This change will affect @camfindlay, possibly

**Comment by camfindlay** [comment]
No trouble I can adjust my fork ;) Good to see mcrypt in by default :+1:

**Comment by dhensby** [comment]
There's no way PHP 5.6 should be the default. I can't think of any production ready project that requires 5.6 and lawd only knows how SS will work with 5.6 see #53 for moving to CentOS 7 and thus PHP 5.4, which is good enough for now.

**Comment by willmorgan** [comment]
We shouldn't be straddling the minimum requirements for projects, IMO. SS travis builds are done against 5.6 iirc and so I don't think that's an argument against it either.

Will Morgan

**Comment by dhensby** [comment]
The argument against it is that 5.6 is an unrealistic expectation of a live environment. The purpose of this project is to provide a development environment that is as close to a production one as possible.

I'm happy to have a 5.6 installer script that people can opt to use instead of the core one, but I've learnt the hard way that using third party repos is one hell of a way to take down your production sites.

If you want to use bleeding edge releases, maybe Ubuntu is a better server for you to use? There's a nice [vagrant box](https://github.com/ThePeach/universal-vagrant) you can use as an alternative.

**Comment by willmorgan** [comment]
OK, after offline discussion, 5.3 is still the default and I'll look at maintaining a separate fork for 5.6.

PR commits updated.

**Pull request merged**
