### PR TITLE
Fixing bugs with xhprof

### PR DESCRIPTION
**Pull request by dhensby**
This fixes some issues with the xhprof installer.

Current known issues:
- .htaccess manipulated repeatedly and has php_flag appended on subsequent provisions
- Needs testing with php 5.5+

cc @Firesphere 

Also, note the main issue with this install was the order of inclusion. It was trying to install before git and the DB were provisioned.

### CODE REVIEW

**Comment by Firesphere** [comment]
That probably is related to the initial issues I ran into :)
No blaming or anything, because the addition is awesome imo :D It just needed a bit more finetuning :) Excellent work on getting the most sorted out :)

**Comment by Firesphere** [comment]
XHprof seems to be removed from the webtatic repo's

**Comment by dhensby** [comment]
Ergh... I improved xdebug a little the other day...

**Comment by Firesphere** [comment]
I still like XHProf better :P It can easily be installed via PECL, so why not try it?

**Comment by dhensby** [comment]
xhprof has really fallen out of favour for me and so I'm going to opt to close this and instead remove xhprof from the vagrant build (unless someone else wants to contribute it)

**Pull request closed without merging**
