### PR TITLE
Define missing Vagrant min version

### PR DESCRIPTION
**Pull request by willmorgan**
~~The 7 box is now discontinued.~~

https://app.vagrantup.com/chef/boxes/centos-7.0
https://app.vagrantup.com/bento/boxes/centos-7.0

Vagrant 1.9 doesn't play nice with the new Bento boxes

### CODE REVIEW

**Comment by dhensby** [comment]
I'm going to close this as it seems the centos-7 box is fine

**Comment by willmorgan** [comment]
@dhensby would you mind keeping this open. I've just tested with `master` and there is definitely something up:

```
[willmorgan@mbp ~/Projects/vagrant-skeleton (master)]$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'bento/centos-7' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
The box 'bento/centos-7' could not be found or
could not be accessed in the remote catalog. If this is a private
box on HashiCorp's Atlas, please verify you're logged in via
`vagrant login`. Also, please double-check the name. The expanded
URL and error message are shown below:

URL: ["https://atlas.hashicorp.com/bento/centos-7"]
Error: The requested URL returned error: 404 Not Found
```

**Comment by dhensby** [comment]
What happens if you run:

```sh
$ mkdir ~/centos-test
$ cd ~/centos-test
$ vagrant init bento/centos-7
$ vagrant up
```

**Comment by willmorgan** [comment]
```
[willmorgan@mbp ~/Projects/vagrant-skeleton (master)]$ mkdir ~/centos-test
[willmorgan@mbp ~/Projects/vagrant-skeleton (master)]$ cd ~/centos-test/
[willmorgan@mbp ~/centos-test]$ vagrant init bento/centos-7
A `Vagrantfile` has been placed in this directory. You are now
ready to `vagrant up` your first virtual environment! Please read
the comments in the Vagrantfile as well as documentation on
`vagrantup.com` for more information on using Vagrant.
[willmorgan@mbp ~/centos-test]$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'bento/centos-7' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
The box 'bento/centos-7' could not be found or
could not be accessed in the remote catalog. If this is a private
box on HashiCorp's Atlas, please verify you're logged in via
`vagrant login`. Also, please double-check the name. The expanded
URL and error message are shown below:

URL: ["https://atlas.hashicorp.com/bento/centos-7"]
Error: The requested URL returned error: 404 Not Found
```

Version:
```
[willmorgan@mbp ~/centos-test]$ vagrant --version
Vagrant 1.9.3
```

I'll update to the latest and get back to you!

**Comment by willmorgan** [comment]
Updating seems to have worked... we therefore require a minimum vagrant version of ~2.0:

```
[willmorgan@mbp ~/centos-test]$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'bento/centos-7' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
==> default: Loading metadata for box 'bento/centos-7'
    default: URL: https://vagrantcloud.com/bento/centos-7
==> default: Adding box 'bento/centos-7' (v201807.12.0) for provider: virtualbox
    default: Downloading: https://vagrantcloud.com/bento/boxes/centos-7/versions/201807.12.0/providers/virtualbox.box
```

**Comment by dhensby** [comment]
I guess we can remove the condition from `Vagrantfile`:

`v.linked_clone = true if Gem::Version.new(Vagrant::VERSION) >= Gem::Version.new('1.8.0')`

I wonder if there's a way to dictate in the `Vagrantfile` that we need v2?

**Comment by dhensby** [comment]
yes, yes there is: https://www.vagrantup.com/docs/vagrantfile/vagrant_version.html

**Comment by dhensby** [comment]
see #134

**Comment by willmorgan** [comment]
I think we are now good to go...

**Pull request merged**
