### PR TITLE
Moving to CentOS 7

### PR DESCRIPTION
**Pull request by dhensby**
- Updated to use CentOS 7 box from Vagrant Cloud
- Updated installers to use new CentOS functions
- Removed iptables (no longer used in CentOS)
- Removed scripts that I'm not able to support right now

### CODE REVIEW

**Comment by dhensby** [comment]
ok, this is basically done now bar one issue, which is that centos 7 doesn't have `/usr/local/bin` on the `PATH` so `sass` and `compass` aren't available as executables.

I think we need to add a .sh file to `/etc/profie.d/`

**Comment by dhensby** [comment]
Right, I think this is ready now. I'm going to test further on a project and then fixup the commits so they actually make sense

**Comment by willmorgan** [comment]
Ready?

**Comment by dhensby** [comment]
I'm still testing it and have noticed a couple things just now like the npm log and incorrect version echo in sass installer

**Pull request merged**
