### PR TITLE
Symlink the logs to /Vagrant to make it easily accessible from the host.

### PR DESCRIPTION
**Pull request by Firesphere**
Fixing issue #61

### CODE REVIEW

**Comment by dhensby** [comment]
Hmm, the problem with this is that the logs folder will then become part of the project working directory.

Also, this is going to be a write to the host file-system which is slower than writing to the guest so we could introduce a fair amount of slowdown.

Lastly, the apache logs are in `/etc/httpd/logs` not `/var/logs/httpd`

**Comment by willmorgan** [comment]
I'm not sure I can see a real need to have logs accessible on the host, and if there is one, then I can't see the problem with temporarily symlinking the directory when needed.

Is there a particular use case here, @Firesphere? I just SSH in to the guest and grep around, personally, but appreciate there are cooler ways to debug.

**Comment by Firesphere** [comment]
Well, it's one of those cases of "Personal preference", I have a realtime logview app on my desktop and laptop pc's, in which I like to easily open the log files.

SSH'ing and grepping around is an option too. It's not a big issue to me, just a thought you might like the idea as well :)

**Comment by dhensby** [comment]
@Firesphere I think it's a cool idea if you have a log reader, but probably not out of the box.

Thanks though. Perhaps your tool can work through an SSH tunnel into the vagrant box?

**Comment by Firesphere** [comment]
Currently, I haven't found one that's suitable. But I agree on your comment, especially to keep the eventual box as low profile as possible, this is overkill.

**Comment by dhensby** [comment]
opening a vagrant ssh and doing `tail -f /etc/httpd/logs/error_log` is what I tend to do.. though it's not pretty

**Pull request closed without merging**
