### PR TITLE
Adding composer's vendor directory to system PATH

### PR DESCRIPTION
**Pull request by willmorgan**
Handy when using Laravel and creating Laravel projects.

### CODE REVIEW

**Comment by willmorgan** [comment]
Actually I just realised this is only temporary - with CentOS it's probably best to put this into `/etc/profile.d`

**Comment by dhensby** [comment]
Good addition in general, but yes, it needs to be symlinked I think.

**Comment by willmorgan** [comment]
Not really much point symlinking it because it's already a symlink to the laravel path within the vendor folder, plus to symlink everything that is installed would be a major pain. I'll see what can be done.

**Comment by willmorgan** [comment]
@dhensby updated following [this advice](http://serverfault.com/questions/102932/adding-a-directory-to-path-in-centos) - `pathmunge` is a function defined in `/etc/profile` which basically scans through all `/etc/profile.d/*.sh` files

**Comment by dhensby** [comment]
I'm happy to add this but I don't want to include config files any more. Can you add it in the script?

**Comment by willmorgan** [comment]
What, using echo? Could do but I can't see a rationale for your decision.

Will Morgan

**Comment by dhensby** [comment]
I'd like to aim for self contained installers, basically. I think these config files make for a painful maintenance procedure especially when upgrading.

**Comment by willmorgan** [comment]
I'm used to doing things the way of content separated from commands :cry:

**Comment by willmorgan** [comment]
Code's updated... at least this will be nice and easy to rebase against the CentOS 7 PR ;)

**Pull request merged**
